/**
 * Markdown report generator
 */

import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs';
import type { AnalysisResult } from '@zava-review/core';

/**
 * Generate a markdown report from analysis results
 */
export async function generateReport(
    result: AnalysisResult,
    workspacePath: string,
    reportType: 'full-analysis' | 'pending-changes'
): Promise<string> {
    const config = vscode.workspace.getConfiguration('zava-review');
    const outputDir = config.get<string>('outputDir', '.zava-review');

    // Create output directory
    const outputPath = path.join(workspacePath, outputDir);
    if (!fs.existsSync(outputPath)) {
        fs.mkdirSync(outputPath, { recursive: true });
    }

    // Generate filename with timestamp
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
    const filename = `${reportType}-${timestamp}.md`;
    const reportPath = path.join(outputPath, filename);

    // Build report content
    const content = buildReportContent(result, reportType);

    // Write report
    fs.writeFileSync(reportPath, content);

    return reportPath;
}

/**
 * Open report in editor
 */
export async function openReport(reportPath: string): Promise<void> {
    const doc = await vscode.workspace.openTextDocument(reportPath);
    await vscode.window.showTextDocument(doc, {
        preview: false,
        viewColumn: vscode.ViewColumn.Beside,
    });
}

function buildReportContent(result: AnalysisResult, reportType: string): string {
    const lines: string[] = [];
    const title = reportType === 'full-analysis'
        ? 'Full Code Analysis Report'
        : 'Pending Changes Analysis Report';

    lines.push(`# ${title}`);
    lines.push('');
    lines.push(`> Generated by **zava-review** on ${result.metadata.timestamp.toLocaleString()}`);
    lines.push('');

    // Summary section
    lines.push('## Summary');
    lines.push('');
    lines.push(result.summary);
    lines.push('');

    // Statistics
    lines.push('## Statistics');
    lines.push('');
    lines.push('| Metric | Value |');
    lines.push('|--------|-------|');
    lines.push(`| Provider | ${result.metadata.provider} |`);
    lines.push(`| Model | ${result.metadata.model} |`);
    lines.push(`| Files Analyzed | ${result.metadata.filesAnalyzed} |`);
    lines.push(`| Total Findings | ${result.metadata.totalFindings} |`);
    lines.push(`| 🔴 Critical | ${result.metadata.bySeverity.critical} |`);
    lines.push(`| 🟡 Warning | ${result.metadata.bySeverity.warning} |`);
    lines.push(`| 🔵 Info | ${result.metadata.bySeverity.info} |`);
    lines.push(`| Duration | ${result.metadata.durationMs}ms |`);
    lines.push('');

    // Quick links if there are critical findings
    if (result.metadata.bySeverity.critical > 0) {
        lines.push('## ⚠️ Critical Issues');
        lines.push('');

        for (const file of result.files) {
            const criticals = file.findings.filter(f => f.severity === 'critical');
            for (const finding of criticals) {
                lines.push(`- **${file.path}:${finding.line}** - ${finding.message}`);
            }
        }
        lines.push('');
    }

    // Findings by file
    lines.push('## Detailed Findings');
    lines.push('');

    const filesWithFindings = result.files.filter(f => f.findings.length > 0);

    if (filesWithFindings.length === 0) {
        lines.push('🎉 No issues found!');
    } else {
        for (const file of filesWithFindings) {
            lines.push(`### 📄 ${file.path}`);
            lines.push('');
            lines.push(`*${file.linesAnalyzed} lines analyzed, ${file.findings.length} finding(s)*`);
            lines.push('');

            // Sort findings by line number
            const sortedFindings = [...file.findings].sort((a, b) => a.line - b.line);

            for (const finding of sortedFindings) {
                const icon = finding.severity === 'critical' ? '🔴' :
                    finding.severity === 'warning' ? '🟡' : '🔵';

                lines.push(`#### ${icon} Line ${finding.line} - ${finding.rule}`);
                lines.push('');
                lines.push(finding.message);

                if (finding.suggestion) {
                    lines.push('');
                    lines.push(`> **💡 Suggestion:** ${finding.suggestion}`);
                }
                lines.push('');
            }
        }
    }

    // Footer
    lines.push('---');
    lines.push('');
    lines.push('*Report generated by [zava-review](https://github.com/your-org/zava-review)*');

    return lines.join('\n');
}
